version: '3.9'
services:
  user-profile:
    image: 369076538622.dkr.ecr.eu-central-1.amazonaws.com/user-profile:1.1.0
    networks: 
      - mongo-net
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    networks: 
      - mongo-net
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    networks:
      - mongo-net
    restart: always # mongo-express depends on mongodb and has to restart
                    # until it can successfully connect to mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
  mongo-net: